"""Build per-zone map images from a WoW 3.3.5a client you own.

Same sources and rules as extract_maps.py, one level deeper: each zone's art is a 4x3
BLP tile grid under Interface\WorldMap\<InternalName>\, and the projection bounds come
from the client's own DBFilesClient\WorldMapArea.dbc - read from the same archives, so
art and bounds cannot disagree about what a zone is called.

Outputs zone-<areaId>.jpg per zone plus zonemaps.ts for the dashboard.
"""
from __future__ import annotations

import io
import struct
import sys
from pathlib import Path

from PIL import Image

from extract_maps import (ARCHIVE_ORDER, CONTENT_H, CONTENT_W, TILE_COLS, TILE_ROWS,
                          build_index)

CONTINENT_MAPS = {0, 1, 530, 571}

# Display names come from the dashboard's own zone table at render time; the dbc's
# internal name is only the art folder. Kept in the TS output for debugging.


def parse_worldmaparea(raw: bytes):
    magic, count, fields, record_size, _strsize = struct.unpack_from("<4siiii", raw, 0)
    assert magic == b"WDBC", f"not a DBC: {magic!r}"
    # 3.3.5a layout: ID, MapID, AreaID, InternalName, LocLeft, LocRight, LocTop,
    # LocBottom, DisplayMapID, DefaultDungeonFloor, ParentWorldMapID.
    assert fields == 11 and record_size == 44, f"unexpected layout {fields}x{record_size}"
    header = 20
    strings = raw[header + count * record_size:]

    def text(off: int) -> str:
        return strings[off:strings.index(b"\0", off)].decode("utf-8", "replace")

    rows = []
    for i in range(count):
        base = header + i * record_size
        rid, map_id, area_id, name_off = struct.unpack_from("<4i", raw, base)
        left, right, top, bottom = struct.unpack_from("<4f", raw, base + 16)
        display_map = struct.unpack_from("<i", raw, base + 32)[0]
        rows.append(dict(id=rid, map=map_id, area=area_id, name=text(name_off),
                         left=left, right=right, top=top, bottom=bottom,
                         display=display_map))
    return rows


def stitch(index, folder: str) -> Image.Image | None:
    tiles = []
    for i in range(1, TILE_COLS * TILE_ROWS + 1):
        key = f"interface\\worldmap\\{folder}\\{folder}{i}.blp".lower()
        entry = index.get(key)
        if not entry:
            return None
        archive, real = entry
        try:
            tiles.append(Image.open(io.BytesIO(archive.read_file(real))).convert("RGB"))
        except Exception:                             # noqa: BLE001 - unreadable tile
            return None
    tw, th = tiles[0].size
    canvas = Image.new("RGB", (tw * TILE_COLS, th * TILE_ROWS))
    for idx, tile in enumerate(tiles):
        canvas.paste(tile, ((idx % TILE_COLS) * tw, (idx // TILE_COLS) * th))
    return canvas.crop((0, 0, CONTENT_W, CONTENT_H))


def main() -> int:
    data_dir, out_dir = Path(sys.argv[1]), Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    index, opened = build_index(data_dir)
    print(f"indexed {len(index)} paths from {len(opened)} archives")

    entry = index.get("dbfilesclient\\worldmaparea.dbc")
    assert entry, "WorldMapArea.dbc not found in archives"
    rows = parse_worldmaparea(entry[0].read_file(entry[1]))

    # Field-order sanity check against the continent row the dashboard already trusts:
    # Azeroth's LocLeft is 18171.97 in every 3.3.5 client.
    azeroth = next(r for r in rows if r["map"] == 0 and r["area"] == 0)
    assert abs(azeroth["left"] - 18171.97) < 5, f"field order wrong: {azeroth}"

    zones = [r for r in rows
             if r["area"] != 0 and r["map"] in CONTINENT_MAPS and r["display"] == -1]
    print(f"{len(zones)} candidate zones in WorldMapArea.dbc")

    built, ts_rows = 0, []
    for z in sorted(zones, key=lambda r: r["area"]):
        img = stitch(index, z["name"])
        if img is None:
            print(f"  {z['name']:22} (area {z['area']}): no complete tile set - skipped")
            continue
        out = out_dir / f"zone-{z['area']}.jpg"
        img.save(out, "JPEG", quality=88, optimize=True)
        built += 1
        ts_rows.append(
            f"  {z['area']}: {{ art: '{z['name']}', map: {z['map']}, "
            f"left: {z['left']:.1f}, right: {z['right']:.1f}, "
            f"top: {z['top']:.1f}, bottom: {z['bottom']:.1f} }},")

    ts = (
        "// Generated by tools/extract_zone_maps.py from the client's own\n"
        "// WorldMapArea.dbc - bounds and art come from the same archive, so they\n"
        "// cannot disagree. Only zones with a complete tile set are listed: presence\n"
        "// in this table is what tells the dashboard a zone can be dived into.\n"
        "export type ZoneMap = {\n"
        "  art: string; map: number; left: number; right: number; top: number; bottom: number\n"
        "}\n\n"
        "export const ZONE_MAPS: Record<number, ZoneMap> = {\n"
        + "\n".join(ts_rows) + "\n}\n"
    )
    (out_dir / "zonemaps.ts").write_text(ts)
    print(f"built {built}/{len(zones)} zone maps + zonemaps.ts")
    return 0 if built else 1


if __name__ == "__main__":
    raise SystemExit(main())
